### ISSUE TITLE
Crash Analyzing Godot Engine App

### ISSUE THREAD

**Issue by ATryder** [google/android-classyshark#199]
I was playing around with Classyshark and noticed that it crashes when attempting to analyze my Godot Engine game Carpe Diem.

apk is available at https://www.inventati.org/1337gallery/games/carpediem/carpediem.html

Source: https://github.com/ATryder/CarpeDiem

**Comment by borisf** [comment]
Can you attach the stack trace please (via running ClassyShark from the command line  ```java -jar classyshark.jar```   )

**Comment by ATryder** [comment]
Sorry, I didn't have my computer in front of me last night.

Logcat stack trace:
```
08-17 08:10:05.624 21236 21236 E AndroidRuntime: FATAL EXCEPTION: main
08-17 08:10:05.624 21236 21236 E AndroidRuntime: Process: com.oF2pks.classyshark3xodus, PID: 21236
08-17 08:10:05.624 21236 21236 E AndroidRuntime: java.lang.OutOfMemoryError: Failed to allocate a 536870928 byte allocation with 25165824 free bytes and 253MB until OOM, target footprint 296362472, growth limit 536870912
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at java.util.Arrays.copyOf(Arrays.java:3161)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at java.io.ByteArrayOutputStream.grow(ByteArrayOutputStream.java:118)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at java.io.ByteArrayOutputStream.ensureCapacity(ByteArrayOutputStream.java:93)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:153)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at com.google.classysharkandroid.utils.IOUtils.copyLarge(IOUtils.java:59)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at com.google.classysharkandroid.utils.IOUtils.copy(IOUtils.java:44)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at com.google.classysharkandroid.utils.IOUtils.toByteArray(IOUtils.java:39)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at com.google.classysharkandroid.activities.ClassesListActivity.doJob(ClassesListActivity.java:237)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at com.google.classysharkandroid.activities.ClassesListActivity.onCreate(ClassesListActivity.java:137)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7835)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:7824)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3298)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3462)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2063)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:107)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:214)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7616)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
08-17 08:10:05.624 21236 21236 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
```

**Comment by borisf** [comment]
It looks like you are getting an out of memory error

 java.lang.OutOfMemoryError: Failed to allocate a 536870928 byte allocation with 25165824 free bytes and 253MB until OOM, target footprint 296362472, growth limit 536870912

When running ClassyShark client on Android. To be honest the Android client was kinda a proof concept, while all the functionality on the desktop.

With that, always happy for pull requests

**Comment by ATryder** [comment]
You can just disregard this issue then. It's not something I need, just thought the author might like to know about it.
