### ISSUE TITLE
Unknown bytecode version

### ISSUE THREAD

**Issue by gitgitwhat** [google/android-classyshark#208]
java.lang.IllegalArgumentException: Unknown bytecode version
        at org.ow2.asmdex.lowLevelUtils.BasicDexFileReader.readHeader(BasicDexFileReader.java:197)
        at org.ow2.asmdex.lowLevelUtils.BasicDexFileReader.parse(BasicDexFileReader.java:184)
        at org.ow2.asmdex.lowLevelUtils.DexFileReader.parse(DexFileReader.java:71)
        at org.ow2.asmdex.ApplicationReader.<init>(ApplicationReader.java:221)
        at org.ow2.asmdex.ApplicationReader.<init>(ApplicationReader.java:198)
        at org.ow2.asmdex.ApplicationReader.<init>(ApplicationReader.java:235)
        at com.google.classyshark.silverghost.translator.dex.DexMethodsDumper.fillAnalysis(DexMethodsDumper.java:105)
        at com.google.classyshark.silverghost.translator.dex.DexMethodsDumper.dumpMethods(DexMethodsDumper.java:84)
        at com.google.classyshark.silverghost.exporter.Exporter.writeMethods(Exporter.java:89)
        at com.google.classyshark.silverghost.exporter.Exporter.writeArchive(Exporter.java:47)
        at com.google.classyshark.silverghost.SilverGhostFacade.exportArchive(SilverGhostFacade.java:151)
        at com.google.classyshark.cli.CliMode.with(CliMode.java:63)
        at com.google.classyshark.Main.main(Main.java:46)
java.lang.IllegalArgumentException: Unknown bytecode version
        at org.ow2.asmdex.lowLevelUtils.BasicDexFileReader.readHeader(BasicDexFileReader.java:197)
        at org.ow2.asmdex.lowLevelUtils.BasicDexFileReader.parse(BasicDexFileReader.java:184)
        at org.ow2.asmdex.lowLevelUtils.DexFileReader.parse(DexFileReader.java:71)
        at org.ow2.asmdex.ApplicationReader.<init>(ApplicationReader.java:221)
        at org.ow2.asmdex.ApplicationReader.<init>(ApplicationReader.java:198)
        at org.ow2.asmdex.ApplicationReader.<init>(ApplicationReader.java:235)
        at com.google.classyshark.silverghost.translator.dex.DexMethodsDumper.fillAnalysis(DexMethodsDumper.java:105)
        at com.google.classyshark.silverghost.translator.dex.DexMethodsDumper.dumpMethods(DexMethodsDumper.java:84)
        at com.google.classyshark.silverghost.exporter.Exporter.writeMethods(Exporter.java:89)
        at com.google.classyshark.silverghost.exporter.Exporter.writeArchive(Exporter.java:47)
        at com.google.classyshark.silverghost.SilverGhostFacade.exportArchive(SilverGhostFacade.java:151)
        at com.google.classyshark.cli.CliMode.with(CliMode.java:63)
        at com.google.classyshark.Main.main(Main.java:46)

**Comment by yijigu7745** [comment]
您好，您发送的邮件我已收到，谢谢。
