### ISSUE TITLE
ArrayIndexOutOfBounds when opening APK

### ISSUE THREAD

**Issue by ansman** [google/android-classyshark#43]
I used this command:

```
$ java -jar ClassyShark.jar -open <path-to-apk>
```

and get the following:

```
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: 2
    at java.util.Arrays$ArrayList.get(Arrays.java:3841)
    at com.google.classyshark.gui.GuiMode.buildAndShowClassySharkFrame(GuiMode.java:67)
    at com.google.classyshark.gui.GuiMode.access$000(GuiMode.java:30)
    at com.google.classyshark.gui.GuiMode$1.run(GuiMode.java:38)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
    at java.awt.EventQueue.access$500(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:709)
    at java.awt.EventQueue$3.run(EventQueue.java:703)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I'm using 5.2

**Comment by borisf** [comment]
bug in documentation, should be java -jar ClassyShark.jar <path-to-apk>
