### ISSUE TITLE
Add fallback when ASMdex fails

### ISSUE THREAD

**Issue by borisf** [google/android-classyshark#89]
Add exception handling here:

at org.ow2.asmdex.ApplicationReader.accept(ApplicationReader.java:338)
at com.google.classyshark.silverghost.translator.apk.ApkTranslator.fillAnalysis(ApkTranslator.java:147)
at com.google.classyshark.silverghost.translator.apk.ApkTranslator.doInspect(ApkTranslator.java:203)

**Comment by borisf** [comment]
fixed here https://github.com/google/android-classyshark/commit/5007d7c9b9eb9a28729ca2d8a8443e413c7fb06c
